services:
  _defaults:
    autowire: true
    autoconfigure: true

  WebEtDesign\SeoBundle\:
    resource: '../../*'
    exclude:
      - '../../DependencyInjection'
      - '../../Entity'

  WebEtDesign\SeoBundle\Twig\SeoTwigExtension:
    arguments:
      - '@service_container'
      - '@parameter_bag'
      - '@WebEtDesign\MediaBundle\Services\WDMediaService'
      - '@WebEtDesign\CmsBundle\Services\WDDeclinationService'
      - '@http_client'
    tags:
      - { name: 'twig.extension' }

  presta_sitemap.dumper_default:
    alias: WebEtDesign\SeoBundle\Service\SitemapDumper
